// Conta pronta para acelerar testes locais sem precisar criar um usuario manualmente.
export const DEV_ACCOUNT = {
  email: 'dev@eureca.local',
  password: 'dev123456',
  name: 'Dev Eureca',
  username: 'dev_eureca',
  role: 'Engenharia de Software',
  bio: 'Conta local para testar publicacoes, curtidas e conversas da Eureca.',
  interests: ['Frontend', 'Backend', 'Comunidade'],
}

export const REGISTER_ROLE_GROUPS = [
  {
    label: 'Tecnologia e Programação',
    options: [
      'Engenharia de Software',
      'Desenvolvimento Frontend',
      'Desenvolvimento Backend',
      'Desenvolvimento Full Stack',
      'Desenvolvimento Mobile',
      'Engenharia Informática',
      'Ciência da Computação',
      'Sistemas de Informação',
      'Arquitetura de Software',
      'DevOps',
      'Site Reliability Engineering',
      'Cloud Computing',
      'Cibersegurança',
      'Segurança da Informação',
      'QA e Testes de Software',
      'Game Development',
      'Blockchain',
      'Inteligência Artificial',
      'Machine Learning',
      'Robótica',
      'Redes e Sistemas',
      'Suporte Técnico',
    ],
  },
  {
    label: 'Dados e Analytics',
    options: [
      'Analista de Dados',
      'Ciência de Dados',
      'Engenharia de Dados',
      'Business Intelligence',
      'Analytics',
      'Estatística',
      'Matemática Aplicada',
      'Pesquisa Operacional',
      'Data Product Manager',
      'Analista de Sistemas',
    ],
  },
  {
    label: 'Design, Produto e Marketing',
    options: [
      'Design UI/UX',
      'Product Design',
      'UX Research',
      'Design Gráfico',
      'Design de Interação',
      'Gestão de Produto',
      'Product Owner',
      'Marketing Digital',
      'Growth Marketing',
      'Comunicação Social',
      'Jornalismo',
      'Publicidade',
    ],
  },
  {
    label: 'Medicina, Saúde e Bem-estar',
    options: [
      'Medicina',
      'Medicina Dentária',
      'Odontologia',
      'Enfermagem',
      'Farmácia',
      'Fisioterapia',
      'Psicologia',
      'Nutrição',
      'Biomedicina',
      'Saúde Pública',
      'Terapia Ocupacional',
      'Radiologia',
      'Análises Clínicas',
      'Medicina Veterinária',
      'Educação Física',
    ],
  },
  {
    label: 'Turismo, Hotelaria e Eventos',
    options: [
      'Turismo',
      'Gestão Hoteleira',
      'Hotelaria',
      'Eventos',
      'Guia de Turismo',
      'Aviação',
      'Gestão de Viagens',
      'Lazer e Recreação',
      'Relações Internacionais',
      'Atendimento ao Cliente',
    ],
  },
  {
    label: 'Gastronomia e Alimentação',
    options: [
      'Gastronomia',
      'Chef de Cozinha',
      'Pastelaria e Confeitaria',
      'Panificação',
      'Enologia',
      'Sommelier',
      'Gestão de Restaurantes',
      'Segurança Alimentar',
      'Tecnologia de Alimentos',
      'Cozinha Internacional',
    ],
  },
  {
    label: 'Engenharias e Arquitetura',
    options: [
      'Engenharia Civil',
      'Engenharia Mecânica',
      'Engenharia Elétrica',
      'Engenharia Eletrotécnica',
      'Engenharia Química',
      'Engenharia de Produção',
      'Engenharia Industrial',
      'Engenharia Ambiental',
      'Engenharia Biomédica',
      'Engenharia de Telecomunicações',
      'Arquitetura',
      'Urbanismo',
    ],
  },
  {
    label: 'Gestão, Negócios e Direito',
    options: [
      'Administração',
      'Gestão',
      'Contabilidade',
      'Finanças',
      'Economia',
      'Recursos Humanos',
      'Empreendedorismo',
      'Vendas',
      'Operações',
      'Logística',
      'Supply Chain',
      'Direito',
      'Gestão Pública',
    ],
  },
  {
    label: 'Educação, Ciências e Humanidades',
    options: [
      'Educação',
      'Pedagogia',
      'Docência',
      'Letras',
      'História',
      'Geografia',
      'Sociologia',
      'Filosofia',
      'Biologia',
      'Química',
      'Física',
      'Artes',
      'Música',
      'Serviço Social',
    ],
  },
  {
    label: 'Outras áreas',
    options: [
      'Agronomia',
      'Agricultura',
      'Moda',
      'Fotografia',
      'Audiovisual',
      'Esportes',
      'Estudante',
      'Pesquisa Acadêmica',
      'Outro',
    ],
  },
]

export const REGISTER_ROLE_OPTIONS = REGISTER_ROLE_GROUPS.flatMap(
  (group) => group.options,
)

export const REGISTER_MAX_INTERESTS = 12

export const REGISTER_INTEREST_GROUPS = [
  {
    label: 'Tecnologia',
    options: [
      'Frontend',
      'Backend',
      'Full Stack',
      'Mobile',
      'DevOps',
      'Cloud',
      'Cibersegurança',
      'IA',
      'Machine Learning',
      'Dados',
      'Open Source',
      'Games',
      'Blockchain',
      'Robótica',
      'Automação',
    ],
  },
  {
    label: 'Saúde',
    options: [
      'Medicina',
      'Medicina Dentária',
      'Enfermagem',
      'Farmácia',
      'Psicologia',
      'Nutrição',
      'Fisioterapia',
      'Saúde Pública',
      'Bem-estar',
      'Veterinária',
    ],
  },
  {
    label: 'Turismo e Gastronomia',
    options: [
      'Turismo',
      'Hotelaria',
      'Eventos',
      'Viagens',
      'Aviação',
      'Gastronomia',
      'Cozinha',
      'Pastelaria',
      'Confeitaria',
      'Panificação',
      'Restaurantes',
      'Vinhos',
    ],
  },
  {
    label: 'Design, Produto e Criação',
    options: [
      'UX',
      'UI Design',
      'Product Design',
      'Design Gráfico',
      'Branding',
      'Fotografia',
      'Vídeo',
      'Música',
      'Arte',
      'Moda',
      'Arquitetura',
      'Escrita',
    ],
  },
  {
    label: 'Negócios e Sociedade',
    options: [
      'Startups',
      'Empreendedorismo',
      'Produto',
      'Marketing',
      'Vendas',
      'Finanças',
      'Economia',
      'Direito',
      'Gestão',
      'Educação',
      'Pesquisa',
      'Sustentabilidade',
      'Impacto Social',
      'Comunidade',
    ],
  },
  {
    label: 'Engenharia e Ciências',
    options: [
      'Engenharia Civil',
      'Engenharia Mecânica',
      'Engenharia Elétrica',
      'Engenharia Química',
      'Biologia',
      'Química',
      'Física',
      'Matemática',
      'Astronomia',
      'Agronomia',
      'Energia',
    ],
  },
]

export const REGISTER_INTEREST_OPTIONS = REGISTER_INTEREST_GROUPS.flatMap(
  (group) => group.options,
)

// Itens usados na navegacao superior da aplicacao.
// Alguns possuem "view", que indica para qual tela interna o botao deve levar.
export const navItems = [
  { label: 'Início', icon: 'home', view: 'home' },
  { label: 'Explorar', icon: 'compass' },
  { label: 'Alertas', icon: 'bell', view: 'alerts' },
  { label: 'Conversas', icon: 'chat', view: 'conversations' },
  { label: 'Perfil', icon: 'user', view: 'profile' },
  { label: 'Ajustes', icon: 'settings' },
]

// Dados visuais da area "Em alta".
// Sao mockados no frontend, ou seja, nao vem do backend por enquanto.
export const trends = [
  { category: 'Technology', title: '#BuildInPublic', posts: '12.4K posts' },
  { category: 'Design', title: 'Figma Config', posts: '8.2K posts' },
  { category: 'Programming', title: 'Rust Language', posts: '5.7K posts' },
  { category: 'Trending', title: '#OpenSource', posts: '3.1K posts' },
]

// Sugestoes de perfis para preencher a interface lateral.
// Tambem sao dados fixos por enquanto.
export const suggestions = [
  { initials: 'MT', name: 'Mia Torres', handle: '@miatorres' },
  { initials: 'JK', name: 'James Kim', handle: '@jameskim_dev' },
  { initials: 'PS', name: 'Priya Sharma', handle: '@priyacodes' },
]
